### ISSUE TITLE
Warning message when starting emacs 23.1.1

### ISSUE THREAD

**Issue by ycp101** [magnars/multiple-cursors.el#115]
- My .emacs configuration file is below

(add-to-list 'load-path "~/.emacs.d/mc/")
(require 'multiple-cursors)
(global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
(global-set-key (kbd "C-.") 'mc/mark-next-like-this)
(global-set-key (kbd "C-,") 'mc/mark-previous-like-this)
(global-set-key (kbd "C-c C-,") 'mc/mark-all-like-this)

- When I start emacs 23.1.1, I get a warning message.

Warning: reference to free variable `rectangular-region-mode'

- When I excute commands like mc/mar-next-like-this, I got an error.

[mc] problem in `mc/execute-this-command-for-all-cursors': Symbol's function definition is void: string-prefix-p

- I tried current version. I also tried 1.3.0 and 1.2.3. But all gave me same errors.

**Comment by jtamagnan** [comment]
Emacs 23.1 was released just shy of 7 years ago. Since this does not seem to be an issue any longer (since emacs 23.3 which was released 5 years ago) should we fix this issue or simply close it? @magnars

**Comment by magnars** [comment]
Close.
fre. 20. mai 2016 kl. 00.07 skrev Jules Tamangan <notifications@github.com>:
