### ISSUE TITLE
(require 'cl)

### ISSUE THREAD

**Issue by michael-heerdegen** [magnars/multiple-cursors.el#120]
Hi,

currently, multiple-cursors-core.el does

    (require 'cl)

at run-time.  This is not good.  Any chance to avoid this?

Before cl-lib.el existed, this would not have been a real issue for me, but now, I indeed don't want to need to require cl in every session.

**Comment by fice-t** [comment]
Flycheck shows the following, which is consistent with the above find function:
`the following functions are not known to be defined: remove-if-not, incf, find-if, count-if, symbol-macrolet (emacs-lisp)`

There's not much left at this point.

@magnars Are you going to require an Emacs version that has `cl-lib` installed? If not, one way that should work is to do this:

```elisp
(unless (require 'cl-lib nil t)
  (require 'cl)
  (defalias 'cl-count-if 'count-if)
  (defalias 'cl-find-if 'find-if)
  (defalias 'cl-incf 'incf)
  (defalias 'cl-remove-if-not 'remove-if-not)
  (defalias 'cl-symbol-macrolet 'symbol-macrolet))
```

**Comment by magnars** [comment]
Thanks! No work at all is a good deal. :+1:

**Comment by chuntaro** [comment]
Run-time error occurs in mc-cycle-cursors.el.

Can you commit the following additional?
```diff
--- multiple-cursors-core.el.orig	2016-02-29 14:43:41.398101800 +0900
+++ multiple-cursors-core.el	2016-02-29 14:38:37.641213800 +0900
@@ -30,6 +30,8 @@
       (defalias 'count-if 'cl-count-if)
       (defalias 'find-if 'cl-find-if)
       (defalias 'incf 'cl-incf)
+      (defalias 'sort* 'cl-sort)
+      (defalias 'remove-if 'cl-remove-if)
       (defalias 'remove-if-not 'cl-remove-if-not)
       (defalias 'symbol-macrolet 'cl-symbol-macrolet))
   (require 'cl))
```

**Comment by magnars** [comment]
:+1:

**Comment by chuntaro** [comment]
Thanks!
