### ISSUE TITLE
Universal argument to mc/insert-numbers causes error

### ISSUE THREAD

**Issue by MrBones118** [magnars/multiple-cursors.el#131]
Hi,
mc/insert-numbers works without argument, or with a numerical argument.

However, C-u mc/insert-numbers causes
'mc/restore-state-from-overlay: Wrong type argument: overlayp, nil'

That said, I'm not sure what you'd use the universal argument to that function for (other than numbering from 4? or maybe from 1?).

**Comment by purcell** [comment]
Fixed by #247.

**Comment by angrybacon** [comment]
The fix makes it impossible to change the default starting value of 0 to 1 like such:

``` emacs-lisp
(advice-add #'mc/insert-numbers :around #'me/insert-number)
(defun me/insert-number (fun arg)
  (funcall fun (if arg arg 1)))
```

**Comment by jtamagnan** [comment]
@angrybacon it still works for me...

**Comment by angrybacon** [comment]
@jtamagnan The advice I use manually passes the value 1 to `mc/insert-numbers`. However isn't [this line][10] supposed to only allow numeric prefixes?

[10]: https://github.com/magnars/multiple-cursors.el/pull/247/commits/19a09d38095930ceba205c581f559c97cc5d631e#diff-cbb27da8c32d3ec1bd210c9ead9a2e2fR36

**Comment by jtamagnan** [comment]
Nope that takes a prefix argument and converts it to an integer if need be, if it recieves an integer it simply returns the original integer

**Comment by angrybacon** [comment]
@jtamagnan Oh ok. It doesn't work since I've updated my packages. I'll investigate further, thanks.

**Comment by jtamagnan** [comment]
I'm working on simply adding a defcustom it should be up soon

**Comment by angrybacon** [comment]
@jtamagnan Awesome, thank you!
