### ISSUE TITLE
mc/mark-next-symbol-like-this doesn't respect the symbol at point

### ISSUE THREAD

**Issue by Wilfred** [magnars/multiple-cursors.el#161]
Given the following C code:

```
void emit_header(FILE *out, char *name) {
    fprintf(out, "%s\n", name);
}

void emit_instr(FILE *out, char* instr, char* operands) {
    fprintf(out, "    %s    %s\n", instr, operands);
}
```

If point is in the middle of the first `fprintf`. `mc/mark-next-symbol-like-this` doesn't mark the next `printf` symbol.

Am I doing something wrong, or is this a bug? There isn't a docstring on this command, so I'm not sure.

**Comment by jtamagnan** [comment]
Joca-bt is correct and documentation has been included to reflect what the functions in question do

**Comment by Wilfred** [comment]
Thanks! :)
