### ISSUE TITLE
Leftover cursor overlays after "Beginning of buffer" or "End of buffer" error

### ISSUE THREAD

**Issue by dgutov** [magnars/multiple-cursors.el#177]
1. `M-x end-of-buffer`, `M-x mc/mark-next-like-this` -> see the error; the cursor won't go away after you press `C-g`.

2. `M-x beginning-of-buffer`, `M-x mc/mark-previous-like-this` -> same.

**Comment by jtamagnan** [comment]
I was unable to reproduce this. Is it still an issue for you?

**Comment by dgutov** [comment]
Yep, looks fixed. Thanks!
