### ISSUE TITLE
Cursors get out of sync.

### ISSUE THREAD

**Issue by robru** [magnars/multiple-cursors.el#178]
I find that if I run `mc/mark-all-symbols-like-this` it correctly selects all instances of that symbols, but if I then hit the backspace key, only the primary cursor deletes while the rest don't move. if I then hit backspace a second time, all cursors will delete, which means the primary cursor will have deleted it's region +1 more character while the rest of the cursors will have only deleted their regions.

If instead of hitting backspace I just type over the region, it works as expected (all regions equally replaced with what I type).

Using a recent git master of emacs for this.

```
$ emacs --version
GNU Emacs 25.0.50.1
```

Any ideas how I might troubleshoot this? I wouldn't be surprised to learn that something is misconfigured locally, but I'm not sure what.

**Comment by magnars** [comment]
It could also be that you're using the master branch of Emacs. I long ago abandoned the idea of supporting the dev branch of Emacs - way too many regressions that would be fixed by time of release.

**Comment by robru** [comment]
Hmm, I just reproduced the same issue with Emacs 24.3.1. So you're saying you don't see this behavior? After you `mc/mark-all-symbols-like-this` and hit backspace, all the symbols are deleted evenly?

**Comment by magnars** [comment]
Okay, good to get that out of the way. :) Yeah, all symbols are deleted evenly here.

What command does backspace run for you? And is that command listed anywhere in `.emacs.d/.mc-lists.el`?

**Comment by robru** [comment]
When I type `C-h c <backspace>` I get `DEL (translated from <backspace>) runs the command backward-delete-char-untabify`, and I do not see it listed in `.mc-lists.el`, which contains:

```
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ))

(setq mc/cmds-to-run-once
      '(
        cua-delete-region
        ))
```

Not sure what other details might be relevant. I'm running on Ubuntu Utopic and I have cua-mode enabled...

**Comment by magnars** [comment]
Yeah, `backward-delete-char-untabify` is in the default list that comes with multiple-cursors.

However, `cua-mode` will remap keybindings based on state. My guess is that DEL is `cua-delete-region` when you have an active region. Moving that over to `mc/cmds-to-run-for-all` (remember to eval the buffer) should solve your issue. :-)

**Comment by robru** [comment]
Ah, excellent, it's working now! Thanks for the quick response!

Any chance we can get `cua-delete-region` put into the default list of `cmds-to-run-for-all` so other cua users don't get bit by this?

**Comment by magnars** [comment]
Yep, already done. :-)

**Comment by robru** [comment]
You rock dude, thanks so much ;-)
