### ISSUE TITLE
Multicursor input does not work in org-mode

### ISSUE THREAD

**Issue by joonro** [magnars/multiple-cursors.el#180]
Hi,

I'm not sure if I'm the only one having this issue - but in org-mode, multicursor input does not work.
Basically when I select multiple lines and invoke `mc/edit-lines`, and then start typing, the letters are typed in the the last line only. Deleting is fine.

In other modes it works fine - it only happens in `org-mode`.

**Comment by magnars** [comment]
What does your `~/.emacs.d/.mc-lists.el` say?

**Comment by joonro** [comment]
Here it is. Thanks for your help!

```lisp
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ignore
        keyboard-escape-quit
        kill-region
        org-force-self-insert
        org-yank
        yank-rectangle
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        electric-newline-and-maybe-indent
        handle-switch-frame
        mouse-set-region
        open-rectangle
        org-edit-special
        org-insert-heading
        org-open-at-mouse
        org-return-indent
        org-self-insert-command
        overwrite-mode
        suspend-frame
        ))
```

**Comment by magnars** [comment]
As you can see, `org-self-insert-command` is in the list of commands to run once. Move it to the other list and evaluate the buffer to fix your issue. :)

**Comment by joonro** [comment]
That fixed it. Thank you so much! Could you please let me know when the option was set? I don't recall setting this .. or is it something I did?

**Comment by magnars** [comment]
At one point, you were prompted "Run this command for all cursors?" and
answered no. :)

**Comment by joonro** [comment]
I must have - I think I did not know what was going on at that time. Thank you again!

**Comment by HeinrichHartmann** [comment]
Same issue here. Thx for the fix.

**Comment by StatelessCat** [comment]
@magnars I think "Run this command for all cursors?" is not the good thing to ask because ansering yes will change the future default behavior of the command. 
Maybe the sentence can be reformulated to be more specific ?

**Comment by jtamagnan** [comment]
@StatelessCat if it were to be changed what would you suggest?

**Comment by anquegi** [comment]
Same issue for me. Solved by @magnars, thanks for this great emacs extension

**Comment by alvarouc** [comment]
same issue here. It was a sneaky question that may take new comers by surprise. I will suggest just getting rid of the question and assume yes. Advanced users could edit this later.

**Comment by magnars** [comment]
Sneaky question or no, it is needed. Emacs functions can do anything. Let's say you make a function to send email. You don't want 15 emails sent by default because you had 15 cursors at the time.
