### ISSUE TITLE
Line break-preserving multiline deletion

### ISSUE THREAD

**Issue by joonro** [magnars/multiple-cursors.el#181]
Is there a way to preserve lines breaks when deleting multiple lines? For example, if I want to delete the the couple of initial spaces from the following lines:

```python
  For i in range(10):
      print(i)

      print(i)
```

If I select the 4 lines and invoke the multiple edit, and press delete key twice, I end up:

```python
For i in range(10):
    print(i)
   print(i)
```

It would be great if there is a way to make it 

```python
For i in range(10):
    print(i)

    print(i)
```

Thanks!

**Comment by magnars** [comment]
`set-rectangular-region-anchor` will let you create cursors only on the lines that have chars. Start with the cursor in front of `For` (not on the start of the line, but after the whitespace). Invoke the command, and move down. You'll see it skips the blank line.

**Comment by joonro** [comment]
Thank you so much for quick reply!
