### ISSUE TITLE
Highlight sexp doesn't work when editing multiple cursors

### ISSUE THREAD

**Issue by AeroNotix** [magnars/multiple-cursors.el#182]

**Comment by jtamagnan** [comment]
Hi @AeroNotix Can we have a bit more information about what function you're talking about? How to reproduce? If this issue persists if you start emacs with the -Q option? ect. Thanks

**Comment by AeroNotix** [comment]
This must've changed recently or something, I just checked now and it's working.

**Comment by jtamagnan** [comment]
Awesome thank you!
