### ISSUE TITLE
only one cursor moves to the right with global-subword-mode

### ISSUE THREAD

**Issue by jipodine** [magnars/multiple-cursors.el#184]
I usually uses global-subword-mode, but with multiple-cursors, only the last cursor moves to the right with either C-right or M-right. Left moves are fine. Without global-subword-mode, everything is fine...

**Comment by magnars** [comment]
Find out what command C-right or M-right is bound to, then edit your `~/.emacs.d/.mc-lists.el` to run it for all cursors.

**Comment by jipodine** [comment]
Indeed, this is the place to look at, as written in the doc ("Make sure to do so before requiring multiple-cursors."). Thank you for your nice reminder.
The first time I tried mc, I did not really understand the question about "doing it for all cursors", because I thought it did not work, and now I remember that my choices are stored here... (And I cleaned them.)
