### ISSUE TITLE
Is it possible to yank the multiple selected regions in the corresponding cursors?

### ISSUE THREAD

**Issue by julior** [magnars/multiple-cursors.el#189]
Let's say that I start multiple cursors and make multiple selections, then move the cursors, and when pasting (yank) it pastes the content of the first region to all the cursors positions. I'd it to paste each selection to the corresponding cursor.

If this is not implemented, I'd like to know if it's feasible, and how can this be implemented.

Thanks

**Comment by magnars** [comment]
- make multiple selections
- copy 
- move cursors
- paste

**Comment by amelio-vazquez-reina** [comment]
I am having the same question. @magnars That seems to only work only if you move the cursors (i.e. stay in the same buffer). Is there any way to be able to yank it on a different buffer? If I copy and then paste on a *different* buffer, I only get the first region (as the OP mentioned).

**Comment by magnars** [comment]
Yes, that is possible too. It's not the same question, tho. ;-)

- make multiple selections
- copy
- press return to disable multiple-cursors-mode
- move to other buffer
- run rectangle-yank, normally with `C-x r y`
