### ISSUE TITLE
Insert spcial character "|"

### ISSUE THREAD

**Issue by yitang** [magnars/multiple-cursors.el#195]
Hi, multiple-cursors is a great package, and I used it almost every day. 

Today I face a problem: I can't insert `|` using mc. I can do with other characters like "@" or quote, and I wonder why `|` is special and how to do that?

**Comment by magnars** [comment]
What command is the key bound to?

**Comment by yitang** [comment]
`|` runs the command self-insert-command, which is an interactive
  built-in function in `C source code'.

It is bound to many ordinary text characters.

(self-insert-command N)

**Comment by magnars** [comment]
There is no special handling of the pipe character in multiple-cursors. Could you try with only multiple-cursors installed?

**Comment by jtamagnan** [comment]
@yitang is this still an issue for you? If so can you give us an example to reproduce this? The mode that you're in and some sample text?

**Comment by yitang** [comment]
@jtamagnan  apologies. I forgot I had this open issues. The problem is not longer exists. I think I made a mistake somewhere.
