### ISSUE TITLE
always ask if do command for all cursors in evil mode

### ISSUE THREAD

**Issue by qizhihere** [magnars/multiple-cursors.el#199]
When i select multiple words, then it always ask if do the command for all cursors, whatever command i do(helm-M-x, evil-next-line and so on).
![ask](http://7sbq2s.com1.z0.glb.clouddn.com/img_links/github/evil-multiple-cursors2.png)

![ask](http://7sbq2s.com1.z0.glb.clouddn.com/img_links/github/evil-multiple-cursors1.png)

**Comment by magnars** [comment]
Evil and Multiple Cursors are the two bastions of taking Emacs where it doesn't want to go, and so they don't interoperate very well at all, unfortunately. 

I don't personally use Evil, but several other Evil users have looked into getting the two to play nicely, but to no avail as of yet.

**Comment by qizhihere** [comment]
Oh, it seems not to be a big problem, i can easily switch off evil by C-z, then it doesn't ask me any more. I just want to see if there has a solution or anyone has encountered this condition before, so i close this issue. thks for your answer :-)
