### ISSUE TITLE
Marmalade: "error during download request: Not found"

### ISSUE THREAD

**Issue by helloncanella** [magnars/multiple-cursors.el#200]
Following the instruction of the developer I've tried to install the package through marmalade.

The response I got from repository was: 'Error during download request: Not found'

**Comment by jtamagnan** [comment]
@magnars the last version of mutiple-cursors that was uploaded to marmalade was December 11 2013. Should we remove the repo from marmalade, update it on marmalade or at least remove it from the readme?

**Comment by jtamagnan** [comment]
@helloncanella I was unable to reproduce this, also it is better to get the repo from git or melpa as it will be more up to day. There seems to be issues with marmalade with certain version which can be seen [here](https://marmalade-repo.org/packages/#download)

**Comment by lunaryorn** [comment]
I'd not bother to remove anything from Marmalade—is that even possible at all?  

This issue is a year old; I don't think that Marmalade is still a thing.

**Comment by magnars** [comment]
There's no UI to remove it, at least. I've removed the mention of marmalade in the readme, tho. About time.

**Comment by lunaryorn** [comment]
👍
