### ISSUE TITLE
Implement a safeguard against absurd numbers of cursors

### ISSUE THREAD

**Issue by vermiculus** [magnars/multiple-cursors.el#206]
When using `mark-all` variants, I sometimes get more than I bargained for and end up freezing emacs. It would be nice to have a maximum number of cursors that `mark-all` variants will obey. Of course, this would need to be overridable somehow.

`browse-file` has functionality similar to this.

**Comment by magnars** [comment]
Not a bad idea. I guess this could be added to the code that inserts a fake cursor, prompting the user once it reaches ~1000 cursors or so?

**Comment by vermiculus** [comment]
I think that would be most efficient, depending on what the message should say. Something like

> You now have 1000 cursors. Do you wish to add the rest? (yes/no)

Keeping in mind that checking the number *beforehand* would require a 'dry run' to find all spots where a cursor would be placed. Before any cursor is placed, it could say:

> 4596 additional cursors will be created. This is over your defined maximum of 1000. Do you wish to continue? (yes/no)

Personally, I like the second option better. If the 'over the maximum' number were something like 1024 then I wouldn't mind (answer yes), but 4500 is pushing the limits of what my emacs can handle (answer no).

**Comment by magnars** [comment]
The second option is better, I agree, but also much more work. You would
have to add the check to any function that adds multiple cursors, with a
different implementation for each. The first option is more about
safeguarding, and can be implemented in one place.

**Comment by vermiculus** [comment]
Door number one it is, then :smile:

**Comment by magnars** [comment]
Want to give it a go?

**Comment by vermiculus** [comment]
I'll give it a shot once I'm home from work -- my mind is split in too many pieces right now :)

**Comment by magnars** [comment]
Do I ever know that feeling! :)
