### ISSUE TITLE
Install Error: tar Not Found

### ISSUE THREAD

**Issue by yuanda** [magnars/multiple-cursors.el#208]
I tried to install multiple-cursors with the following commend in Emacs:

    M-x package-install multiple-cursors

Then it gave the following 'Not found' error:

    http://melpa.milkbox.net/packages/multiple-cursors-20150101.1431.tar: Not found

**Comment by magnars** [comment]
Sounds like you need to do a `package-list-packages` first to get an updated list of packages.

**Comment by jtamagnan** [comment]
Closed because this is a problem that happens often, is unrelated to multiple-cursors, and is close to a year old
