### ISSUE TITLE
Ability to unmark all cursors

### ISSUE THREAD

**Issue by lengstrom** [magnars/multiple-cursors.el#209]
Hi, Is there a way to unmark every cursor on the page?

**Comment by magnars** [comment]
I'm not entirely sure what you mean, but:

- if you want to remove all extra cursors, press enter
- if you want to deactivate regions, press C-g

**Comment by lengstrom** [comment]
I guess I meant a method of unmarking all the cursors programmatically, sorry for not making that clear!

**Comment by magnars** [comment]
In that case you're looking for `(mc/remove-fake-cursors)`
