### ISSUE TITLE
Inserting comma

### ISSUE THREAD

**Issue by rrichmond** [magnars/multiple-cursors.el#210]
When I try to insert a comma at multiple cursors, it only inserts at the first one. My guess is its a problem with the regular expressions that may be being used in multiple-cursors. Any suggestions?

**Comment by magnars** [comment]
Find out what command is inserting the comma with `C-h k ,`, open `~/.emacs.d/.mc-lists.el`, and move that command from `mc/cmds-to-run-once` to `mc/cmds-to-run-for-all`.

**Comment by rrichmond** [comment]
easy enough. thanks!
