### ISSUE TITLE
"Unmark cusor on click"

### ISSUE THREAD

**Issue by MagisDing** [magnars/multiple-cursors.el#211]
The function "add-cursor-on-click" is amazing. Is it possible to make the function "remove-cursor-on-click" available? Seems it could be quite handy along with "mark-all-like-this"

**Comment by magnars** [comment]
Sounds entirely doable. Want to give it a shot?

**Comment by MagisDing** [comment]
Hi, Magnars, I am not quite familiar with the beautiful elisp and it is ashamed I couldn't make it. But I still want to put it on the "wish list".

**Comment by lewang** [comment]
A journey of a thousand steps starts with one.

- Chinese proverb

**Comment by jtamagnan** [comment]
This feature was apparently added in commit 40eb74e
