### ISSUE TITLE
Query per cursor

### ISSUE THREAD

**Issue by MrBones118** [magnars/multiple-cursors.el#212]
Sometimes I find I want to do a different thing for each cursors half way through editing.
In this case it'd be great to have multiple-cursors-query-user

Then I could type all at once
(define-key map (kbd "
(define-key map (kbd "
(define-key map (kbd "

And then hit multiple-cursors-query-user and insert a different key combo on each line.

**Comment by magnars** [comment]
If you want to insert a unique piece of text at each cursor, here's one way to do that:

```el
(defun prompt-for-insert ()
  (interactive)
  (insert (read-string "Insert: ")))
```

Bind that to a key, and you'll get a prompt for every cursor. :)

**Comment by MrBones118** [comment]
Awesome

**Comment by lewang** [comment]
`query-replace` with recursive-edit may be a better tool for this job.

On Thu, Aug 13, 2015 at 8:38 AM, MrBones118 <notifications@github.com>
wrote:

> Awesome
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magnars/multiple-cursors.el/issues/212#issuecomment-130654340>
> .
>



-- 
Le
