### ISSUE TITLE
One command select this word & next word like it

### ISSUE THREAD

**Issue by bgvianyc** [magnars/multiple-cursors.el#213]
Sublime has this functionality, doesn't seem this can be done with MC unless expand-region is done first.

ctrl + d: Select the current word and the next same word

**Comment by jtamagnan** [comment]
Maybe it would be better to just put something like this into your config

```lisp
  (defun select-word-and-next (arg)
    (interactive "p")
    (mark-word)
    (mc/mark-next-like-this arg))
```

**Comment by bgvianyc** [comment]
Considering this is the first feature highlighted on the first slide of the main page(www.sublimetext.com) of what is currently one of the most popular text editors, it seems like it would make sense to make it standard in the multiple-cursors package.

**Comment by jtamagnan** [comment]
After watching the video I understand what you mean. It seems like you don't like the default behavior of mc/mark-next-like-this (which is often bound to "C->" but can be bound to anything like "C-d") when it is called without a region being selected. By default it places a cursor on the next line. I agree that it would be nice if when no region were active it would highlighed the word at the point and then placed a cursor a the next occurance of the word. That seems like it would be a pretty easy change.

My idea for implementing this change would be to simply add a variable that can toggle between the default behavior and this new behavior that way by default people would not have to change their workflows and for us who would like this new behavior all we would have to do is add a single line in our config files to toggle the new behavior.

@magnars would you be ok with this type of change?

**Comment by magnars** [comment]
Good analysis. I think a separate command is better than a feature flag in
this case, tho.
fre. 4. des. 2015 kl. 17.41 skrev jtamagnan <notifications@github.com>:

**Comment by jtamagnan** [comment]
I added this feature as a seperate function called mc/mark-next-like-this-word in the above pull request

**Comment by jtamagnan** [comment]
Should it mark the word or the symbol?

**Comment by magnars** [comment]
That's the eternal question. We've solved this so far in multiple-cursors
with offering both versions.

**Comment by jtamagnan** [comment]
I followed suit and added mc/makr-next-like-this-symbol

**Comment by jtamagnan** [comment]
Should this issue be closed as well?

**Comment by magnars** [comment]
That seems like a good idea. Feel free to do so as your first action as a collaborator on this repo. :-) Thanks for your efforts so far!
