### ISSUE TITLE
doesn't work with spacemacs?

### ISSUE THREAD

**Issue by rebcabin** [magnars/multiple-cursors.el#217]
I recently switched to spacemacs (because I want to evangelize VIM users on org-mode, and spacemacs has all kinds of support for VIM users), but found that multiple cursors installed but didn't work at all.  I have a super-vanilla instance of spacemacs, so the problems should be easy to repro.

**Comment by lewang** [comment]
are you aware of https://github.com/magnars/multiple-cursors.el/pull/216 ?

**Comment by rebcabin** [comment]
I am now aware of #216. Thanks.
