### ISSUE TITLE
Add a cursor at the current main cursor position?

### ISSUE THREAD

**Issue by Tonix-Tuft** [magnars/multiple-cursors.el#220]
Hi, 
the feature `mc/add-cursor-on-click` is very useful, I would like to ask you if there's a way to simply add a steady cursor at the current main cursor's position and then, when you have added all the cursors you need where you need them, you kinda "stage" them and from then on whatever you do on your main cursor (move it, insert a letter, etc.), changes are reflected in all the cursors you have added until that moment.

For example, if I have a buffer with the following text:

```
>Some text on line1

Some text on line3

Some text on line5

Some text on line7
_____________________________________________
Minibuffer

```
And the main cursor `>` is at `Some text on line1`, if I need to place a cursor on line 3 too, I can go to that line with the main cursor and place a "steady" cursor there with some fancy function like `mc/add-cursor` at that position:

```
Some text on line1

>Some text on line3

Some text on line5

Some text on line7
_____________________________________________
Minibuffer
M-x mc/add-cursor
```
Ending up in a situation like this:

```
Some text on line1

%>Some text on line3

Some text on line5

Some text on line7
_____________________________________________
Minibuffer
M-x mc/add-cursor
```
Where `%` represents a steady cursor. Then I move the main cursor to line 5 (the steady cursor remains firm at its position for now):

```
Some text on line1

%Some text on line3

>Some text on line5

Some text on line7
_____________________________________________
Minibuffer
M-x mc/add-cursor
```
And add another steady cursor:

```
Some text on line1

%Some text on line3

%>Some text on line5

Some text on line7
_____________________________________________
Minibuffer

```
Move on line 7, and again add a cursor:

```
Some text on line1

%Some text on line3

%Some text on line5

%>Some text on line7
_____________________________________________
Minibuffer

```
Then I move the main cursor to line 1:
```
>Some text on line1

%Some text on line3

%Some text on line5

%Some text on line7
_____________________________________________
Minibuffer

```
And type something like "M-x mc/stage-cursors":
```
>Some text on line1

%Some text on line3

%Some text on line5

%Some text on line7
_____________________________________________
Minibuffer
M-x mc/stage-cursors
```
From now, whatever I do with the main cursor (move it, insert a letter, delete a letter, etc.), that change will be reflected in all the "steady" cursors which have been "staged":

```
>ome text on line1

%ome text on line3

%ome text on line5

%ome text on line7
_____________________________________________
Minibuffer

```

Such a feature will be really useful and you don't have to use the mouse to add cursors where you want them, you can also bind the `mc/add-cursor` to a macro, etc.

What do you think?

**Comment by magnars** [comment]
```
(defun mc/add-cursor ()
  (interactive)
  (mc/create-fake-cursor-at-point))
```

Bind this to a key. When you want to breathe life into the steady cursors, do `M-x multiple-cursors-mode`.

**Comment by Tonix-Tuft** [comment]
Thank you very much! That's it.

**Comment by magnars** [comment]
:)

**Comment by Tonix-Tuft** [comment]
Can we also remove a cursor once we add it with `mc/add-cursor` if we add one by mistake?
