### ISSUE TITLE
mc/mark-next-lines and some other mc/ commands clear the buffer

### ISSUE THREAD

**Issue by srustamo** [magnars/multiple-cursors.el#221]
In a buffer, say with this text:

text1234567
text1234567
text1234567

if 'mc/mark-next-lines' is run on the first line, the buffer is cleared and "mc/mark-next-lines" text is inserted in the first line. I use 'ivy', 'evil' modes, but disabling these and running 'mc/mark-next-lines' still clears the buffer as described above.

**Comment by magnars** [comment]
This does not happen when you run with multiple cursors alone. There is a bad interaction with one of your installed packages. If you can figure out which one it is, I can take a look at it.

**Comment by srustamo** [comment]
Disabling both 'ivy" and 'evil' modes does not help, I still get the
reported behavior.

Any other reason, which you might've encountered for this behavior?

Thanks.

**Comment by srustamo** [comment]
Resetting mc/cmds-to-run-for-all helped.
