### ISSUE TITLE
multiple-cursors fails to load on emacs 25.0

### ISSUE THREAD

**Issue by sobolews** [magnars/multiple-cursors.el#224]
Hi! First of all, thank you for multiple-cursors. I use it every day and it is unbelievably useful!

I recently tried out emacs 25.0 and found that multiple-cursors wouldn't load. The output of `M-x emacs-version` is:
`GNU Emacs 25.0.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.10.8) of 2015-11-12`

The debugger backtrace is attached. The same error occurs with both the melpa version and the current master branch.
[mc-backtrace.txt](https://github.com/magnars/multiple-cursors.el/files/34556/mc-backtrace.txt)

**Comment by magnars** [comment]
Thanks for the report. I generally don't support development versions since there are often regressions that don't make it into the final build. I'll keep an eye out for this one when the new version is released.

**Comment by lunaryorn** [comment]
@sobolews Can you try whether the error still occurs on the latest Emacs 25 pretest?

**Comment by purcell** [comment]
Works for me in a very recent Emacs `master` build.

**Comment by magnars** [comment]
Excellent. Thanks for testing, Steve.
