### ISSUE TITLE
Multiple cursors in several window?

### ISSUE THREAD

**Issue by Silex** [magnars/multiple-cursors.el#225]
Hello,

Is it possible to have multiple cursors over various windows? I realise this behavior is almost built in emacs if you just cycled all windows for all key pressed... maybe you know of an alternative way?

**Comment by magnars** [comment]
Sounds like it would probably be easier to make than multiple-cursors. But it's not something this package is rigged to do.

**Comment by Silex** [comment]
Alright, so I infer there's nothing you know of. So far I did it using macros but it's not as fluid as when using multiple cursors. Thanks for the info!
