### ISSUE TITLE
mc/mark-all-in-region-regexp

### ISSUE THREAD

**Issue by trosendal** [magnars/multiple-cursors.el#230]
Thanks for the great package; I really love using multiple cursors! I have a problem with my goto function that I use in your tool: `mc/mark-all-in-region-regexp`. When I run `mc/mark-all-in-region-regexp` and ask for matched to the regular expression `^` (start of line of the highlighted lines) or `$`(end of line of the highlighted lines) then emacs freezes and I am forces to kill the process. Am I misinterpreting the regular expressions or is this a bug?

**Comment by magnars** [comment]
That was easy to reproduce, at least. It crashed my emacs hard. Thanks for the report.
