### ISSUE TITLE
Please bind mc/add-cursor-on-click to the standard Alt+Shift + mouse-click

### ISSUE THREAD

**Issue by amynbe** [magnars/multiple-cursors.el#233]
Hi Magnars, what do you think of this suggestion:

please add this binding by default:
        `(global-set-key (kbd "M-S-<mouse-1>") 'mc/add-cursor-on-click)`

This is kinda the standard in other editors and is AFAIK unbound in emacs.
And remove the corresponding sections in the README about binding mc/add-cursor-on-click.

**Comment by jtamagnan** [comment]
Multiple cursors binds no keys to the global map and lets the user choose all of his own bindings and I believe it would be best to keep it that way
