### ISSUE TITLE
Please tag the latest stable release

### ISSUE THREAD

**Issue by nispio** [magnars/multiple-cursors.el#242]
There has not been a new "release" of multiple-cursors since 2013.  (see [releases page](https://github.com/magnars/multiple-cursors.el/releases))  I need to cut through some red tape which involves requesting permission to run external software (ie multiple-cursors) and I must call out a specific version of the software in my request.

This may sound like a strange request, but would you please consider tagging the latest stable release with a version number?  Thanks in advance.

**Comment by jtamagnan** [comment]
@magnars I tagged the last release as 1.4.0 and bumped the version number. This should also help with melpa stable.
