### ISSUE TITLE
Reverse region only works on first cursor

### ISSUE THREAD

**Issue by jtamagnan** [magnars/multiple-cursors.el#245]
I have an issue running `reverse-region` on multiple cursors at once. It only affects the first cursor's region. Then that first region is de-selected and nothing happens to the other regions (they remain highlighted and not reversed).

When I run the command it does not prompt whether or not I want to run the command for one or multiple cursors. `reverse-region` is not in `mc/cmds-to-run-once` or in `mc/cmds-to-run-for-all`. I then manually added `reverse-region` to `mc/cmds-to-run-for-all` executed the code and tried again but once again the other regions were not reversed.

I am running the version of multiple-cursors that is on melpa and I am on the master branch of emacs-git. Version: `GNU Emacs 25.1.50.1 (x86_64-pc-linux-gnu, GTK+ Version 2.24.28) of 2016-01-04`

**Comment by magnars** [comment]
This works for me, but only after binding it to a keybinding. Are you running the command with M-x? That does not work (as listed under [Known limitations](https://github.com/magnars/multiple-cursors.el#known-limitations)).

**Comment by jtamagnan** [comment]
Right... My bad :)
