### ISSUE TITLE
Add ability to set a default for the starting number of mc/insert-numbers

### ISSUE THREAD

**Issue by angrybacon** [magnars/multiple-cursors.el#248]

**Comment by magnars** [comment]
You can prefix the command to insert higher numbers. `C-u 15 mc/insert-numbers` would start at 15. Would that suffice?

**Comment by angrybacon** [comment]
Sorry I should have been more clear. In most of my use cases of `mc/insert-numbers`, I start the insert from 1. This requires me to add a prefix every time. Generally speaking, it is more likely that I will want to start at 1 rather than 0.

I am not so proficient with Elisp in general, so I prefer to raise an issue instead of a pull request. However I believe it has to do with this: https://github.com/magnars/multiple-cursors.el/blob/6a62e60bf2920b0790ce27dfce8afd7c9f079f80/mc-separate-operations.el#L36-37.

A customizable variable instead of the `0` would do it I guess?

**Comment by magnars** [comment]
Yep, that would do it. :)

**Comment by jtamagnan** [comment]
Would we be better off letting people just advice the function?
``` elisp
(defun mc/insert-number-start (old-function arg)
  (funcall old-function (if arg arg 1))) ;; change one to the value that you want to start at
(advice-add #'mc/insert-numbers :around #'mc/insert-number-start)
```

**Comment by lunaryorn** [comment]
@jtamagnan I don't think that you should use advises for what a customize option would cover.  Advises should remain the very last resort, and not a regular customisation tool.

**Comment by jtamagnan** [comment]
@lunaryorn I agree, I simply thought that it could be an alternative if we didn't want to add that extra variable to the code and if only a few people thought that they wanted it. It could have then later gone in some "recipes" section in the readme or wiki. I do agree that it should be easy to add and that we might as well

**Comment by jtamagnan** [comment]
Feature added in be149f9
