### ISSUE TITLE
Can emacs set multiple cursors like atom?

### ISSUE THREAD

**Issue by cmal** [magnars/multiple-cursors.el#263]
Can emacs set multiple cursors like atom? just hold <Ctrl> and mouse left click, click, click...
I found it is difficult when I want to set the cursors at positions which are not easy to go to by keyboard.
But thank you for your excellent job, it really helps me a lot.

**Comment by jtamagnan** [comment]
Does this section of the readme solve your issue? https://github.com/magnars/multiple-cursors.el#binding-mouse-events
