### ISSUE TITLE
Add cursors interactively

### ISSUE THREAD

**Issue by sumproxy** [magnars/multiple-cursors.el#265]
I'd like to be able to add cursors interactively, like with e.g. query-replace, where you type a string and then press 'y' to replace 'n' to skip... well you know the rules. In case of multiple cursors it would be nice to have the same functionality for mc/mark-next-like-this, so something like mc/query-mark-next-like-this and mc/query-mark-previous-like-this would be really awesome.
Not sure if issue #44 references something like that.

**Comment by magnars** [comment]
You can get an approximation of this feature using `mc/mark-more-like-this-extended`. It's a little less intuitive than the y/n query approach, but faster once learned.

**Comment by sumproxy** [comment]
Will try it out, thanks
