### ISSUE TITLE
insert-char

### ISSUE THREAD

**Issue by gdkrmr** [magnars/multiple-cursors.el#266]
calling insert-char with multiple cursors asks for every cursor separately what to insert. I would expect to choose the character only once and to have it inserted for every cursor.

**Comment by jtamagnan** [comment]
There isn't a way around that currently. What is your use case?

**Comment by gdkrmr** [comment]
in ess the , is bound to `ess-smart-comma` which is a function that inserts a comma with the right spacing. The function does not work with multiple cursors, so I tried to get around it with `insert-char` but it didn't work either.

https://github.com/emacs-ess/ESS/blob/ffc0d133547f2d86f5c0493bd519520617be2acf/lisp/ess-inf.el#L3009

**Comment by jtamagnan** [comment]
Since it doesn't seem like you'll be able to use smart comma either way why not simply bind `,` to `self-insert-command`

**Comment by gdkrmr** [comment]
this is probably the easiest solution. Thanks!

**Comment by gdkrmr** [comment]
https://github.com/magnars/multiple-cursors.el/issues/229 is related?

**Comment by jtamagnan** [comment]
Yeah its related to being asked over and over again.

**Comment by jtamagnan** [comment]
You might also want to try to only bind it when you're in multiple cursor mode
