### ISSUE TITLE
adding comma

### ISSUE THREAD

**Issue by pkhoueiry** [magnars/multiple-cursors.el#272]
Hi,
In mc mode followed by, for instance, "edit-end-of-lines" we cannot add a comma to all lines. Only the main cursor adds a comma. How to circumvent this behavior ?
Many thanks

**Comment by magnars** [comment]
Check your `.mc-lists.el` file for the command that your `,` invokes, and remove it from the do-once list.

**Comment by zenspider** [comment]
@pkhoueiry if this has been resolved for you, please close.
