### ISSUE TITLE
Making DWIM backspace compatible with multiple-cursors

### ISSUE THREAD

**Issue by kootenpv** [magnars/multiple-cursors.el#273]
Great work on mc! I have been using it for a long time. I was wondering if there is a way to make multiple-cursors to work with the following function:

```emacs
(defun backspace-blank-lines-or-char ()
  (interactive)
  (cond
   ((region-active-p) (delete-region (region-beginning) (region-end)))
   ((looking-back "\n\n\\s-+")
    (while (or (looking-back "\\s-") (looking-back "\n"))
      (delete-char -1))
    (insert "\n\n")
    (indent-for-tab-command))
   ((looking-back "\n\n\n") (previous-line) (delete-blank-lines) (next-line))
   ((looking-back "\n\n") (previous-line) (delete-blank-lines))
   ((looking-back "\n\\s-+") (just-one-space) (delete-char -2) (just-one-space))
   (t (backward-delete-char 1)))
  )
```

Any idea if it possible?

**Comment by magnars** [comment]
I don't see any reason it shouldn't be. As far as I can tell, it should just work.

**Comment by kootenpv** [comment]
@magnars Could it be a bug?  Actually decreased the code:

    (defun backspace-blank-lines-or-char ()
      (interactive)
      (cond
       ((region-active-p) (delete-region (region-beginning) (region-end)))
       (t (backward-delete-char 1)))
      )

But the same problem is there. Could you test it?

I use `mc/mark-next-like-this`, then start typing (and thus overwriting), which works, but then doing a backspace only works on the first occurrence.

**Comment by magnars** [comment]
Could you take a quick look for the misbehaving commands in your ~/.emacs.d/.mc-lists.el file?

**Comment by kootenpv** [comment]
Not sure what I'm looking for, so I'm posting it:

```emacs
(setq mc/cmds-to-run-for-all
      '(
        backward-delete-word
        beginning-of-buffer
        kill-line-or-region
        undefined
        wgrep-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        backspace-blank-lines-or-char
        handle-select-window
        magit-status
        mouse-set-region
        smart-beginning-of-line
        smart-switcher
        ))
```

**Comment by magnars** [comment]
Please note that your `backspace-blank-lines-or-char` has been added to your "commands to run once" list. You have at one point or another answered "no" to "do this for all cursors". Move it to the other list for the desired behavior.

Please also note that `M-x` does not work too well with multiple-cursors.

Happy holidays! :)

**Comment by kootenpv** [comment]
Indeed, quite obvious, that fixed it :) 

Happy holidays to you too as well, and thanks for the fast follow up!
