### ISSUE TITLE
Multiple-cursors in Spacemacs without Evil

### ISSUE THREAD

**Issue by teodorlu** [magnars/multiple-cursors.el#274]
Hello!

Thanks for this great plugin. Huge value add to Emacs, especially from users coming from Sublime.

I like Spacemacs for all the curation. I've found [some](https://github.com/syl20bnr/spacemacs/issues/2669) [threads](https://github.com/magnars/multiple-cursors.el/issues/17) related to Multiple-Cursors and Spacemacs. They both discuss using Evil with vim-style editing.

_Do you know if anyone has used or tried to use Multiple cursors on Spacemacs with Hybrid or Emacs editing styles?_

**Comment by magnars** [comment]
That should just work out of the box, as far as I can tell. The problem with using MC with Evil is the shenanigans needed to simulate vim's cursor position, which is quite different from Emacs'.

**Comment by teodorlu** [comment]
Okay, thanks. I'll have a look and see if I can get things working.

**Comment by teodorlu** [comment]
Yup, you were right. My `dotspacemacs/user-config` now looks something like this:
```elisp
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."

  (require 'multiple-cursors)
  (global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
  (global-set-key (kbd "C->") 'mc/mark-next-like-this)
  (global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
)
```
