### ISSUE TITLE
issue with deleting multiple lines

### ISSUE THREAD

**Issue by przbadu** [magnars/multiple-cursors.el#275]
First, thanks for your wonderful package. I have been playing around with emacs from last couple weeks and I found your emacs-rocks video and got interested in emacs. And thanks for that too 👍 

I have installed `multiple-cursors` using `melpa` package manager with these keybindings:

![multiple-cursor-bindings](https://cloud.githubusercontent.com/assets/4189129/22200993/c3f8e410-e189-11e6-9bcd-6d54071c96d7.PNG)

Now, working part for me is, `C->` or `C-<`, etc is adding multiple cursors but when I hit `delete` or `C-d` or `C-k` or `C-S-delete` only first line is affecting and rest of the lines remains unchanged. 

but If I start typing something, it will add texts in all the lines.

May be below screencast will help understand what I am talking about

![multiple-cursor-issue](https://cloud.githubusercontent.com/assets/4189129/22201057/1e3ab386-e18a-11e6-8ea0-cffd83f56e37.gif)

As you can see above, If I add text it add properly for all multiple cursors, but if I delete anything it only happens for first line.

Thanks

**Comment by magnars** [comment]
Please check your `~/.emacs.d/.mc-lists.el` file for the command in question. At some point you have probably answered "no" to the question "Do this for all cursors?", landing the command in the `mc/cmds-to-run-once`-list. Move the command to the `mc/cmds-to-run-for-all` and evaluate the buffer to resolve this issue.

**Comment by przbadu** [comment]
ok, so this is what i had in my `.mc-lists.el`

```
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ace-jump-mode
	ace-jump-move
	keyboard-escape-quit
	))

(setq mc/cmds-to-run-once
      '(
	ido-find-file
	list-buffers
	rspec-verify-matching
	smex
	sp-backward-delete-char
	sp-delete-char
	sp-kill-hybrid-sexp
	sp-kill-word
	suspend-frame
	))
```

I changed it to:

```
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ace-jump-mode
	ace-jump-move
	keyboard-escape-quit
	sp-backward-delete-char
	sp-delete-char
	sp-kill-hybrid-sexp
	sp-kill-word
	))

(setq mc/cmds-to-run-once
      '(
	ido-find-file
	list-buffers
	rspec-verify-matching
	smex
	suspend-frame
	))
```

And now delete, kill etc are working great. thanks a lot @magnars .

Do you think those lists inside `mc/cmds-to-run-once` are okay, or should I move everything to `mc/cmds-to-run-for-all`?

Thanks
