### ISSUE TITLE
Two cursors in same time

### ISSUE THREAD

**Issue by thomasluquet** [magnars/multiple-cursors.el#276]
hi, i don't know if it is a bug or a bad config,
but i have two cursors the classic one (orange), and the multiple-cursor (grey)

![two cursor](http://i.giphy.com/l0Ex8ucPPHQ9GkQV2.gif)

It is really anoying and i don't know what to do....

**Comment by nispio** [comment]
You made one more cursor than you should have.  Set the mark at the beginning of line 4 and move the point to the beginning of line 6 (not line 7).

**Comment by thomasluquet** [comment]
Ok i think the diffrence between region and rectangle was not clear for me.
