### ISSUE TITLE
add cursors with keyboard

### ISSUE THREAD

**Issue by zombiefungus** [magnars/multiple-cursors.el#283]
Sorry if this is already implemented but didn't find a way to do it. I know you can add cursor with mouse events, but what about keyboard shortcuts? Say for example C-return or whatever to add a cursor at current position?

Thanks :)

**Comment by nispio** [comment]
Related: #220 

Basically you need to use `mc/create-fake-cursor-at-point` to add cursors, and then activate `multiple-cursors-mode` when you are done adding cursors.
