### ISSUE TITLE
Cannot insert period with multiple cursors

### ISSUE THREAD

**Issue by computersarecool** [magnars/multiple-cursors.el#286]
Hi,
Great package - very useful.
When I select multiple things (with multiple cursors) and I press `.` only the first item gets the period.
Is there a way to force a period for all cursors?

**Comment by magnars** [comment]
Please check your `~/.emacs.d/.mc-lists.el` file for the command in question. At some point you have probably answered "no" to the question "Do this for all cursors?", landing the command in the `mc/cmds-to-run-once`-list. Move the command to the `mc/cmds-to-run-for-all` and evaluate the buffer to resolve this issue.

**Comment by computersarecool** [comment]
Awesome. Thanks for the help and the package
