### ISSUE TITLE
Add option to not execute a command

### ISSUE THREAD

**Issue by theldoria** [magnars/multiple-cursors.el#289]
If I use a command yet unlisted In `.mc-lists`, I get asked whether I want it to be run once or for all cursors.

However, sometimes I hit the wrong command and would like to additionally have the option to abort it's execution, because it may make no sense at all to execute it or it may be terribly wrong.

**Comment by magnars** [comment]
In that case, just press C-g.
man. 12. jun. 2017 kl. 05.40 skrev theldoria <notifications@github.com>:
