### ISSUE TITLE
mc/align-points ?

### ISSUE THREAD

**Issue by zenspider** [magnars/multiple-cursors.el#291]
I frequently use `align-regexp` but sometimes it is too hard to come up with a proper regexp to align things (esp if the chars are repeated, think comma or colon in args). But sometimes it is really easy to navigate to the things I want to align... multiple-cursors seems like an ideal candidate to put this. Are you interested in adding such a feature?

**Comment by nispio** [comment]
Take a look at the command `mc/vertical-align-with-space`, and see if it does what you need.

**Comment by zenspider** [comment]
Neeeeeevermind. Hah! You beat me.

I *Just* found that. 😛
