### ISSUE TITLE
mc/mark-all-in-region-regexp bug when exactly one match

### ISSUE THREAD

**Issue by nispio** [magnars/multiple-cursors.el#293]
When invoking `mc/mark-all-in-region-regexp` on a region with exactly one match, the function mistakenly thinks that no matches were found, and signals an error.  This causes the a fake cursor to get left behind without properly enabling `multiple-cursors-mode`.

To reproduce, type "abcdef" in a buffer, and mark it as the active region.  Then do `M-x mc/mark-all-in-region-regexp RET c RET` and you will get a lisp error and see that a fake cursor gets left at the `d`.

**Comment by Fuco1** [comment]
The same error exists in `mc/mark-all-in-region`.

I don't really understand your fix, why did you change the condition to `(< (mc/num-cursors) 3)`?

Can't we only do `(car (mc/all-fake-cursors))` in to assign `first`?
