### ISSUE TITLE
mc/mark-next-like-this seems to call itself when repeatedly invoked

### ISSUE THREAD

**Issue by bwo** [magnars/multiple-cursors.el#299]
(The same is true for several other functions, but it presumably has the same origin)

The following is unexpected behavior:

 1. select a region of interest
 2. M-x mc/mark-next-like-this; enter — puts a cursor at the next matching region. Ok!
 3. M-x (mc/mark-next-like-this comes up as the first option), enter — puts a cursor at the next matching region. Great!
 4. but now, I'm in the minibuffer *again*, even though I didn't hit M-x. If I hit enter, I mark the next-like-this, and step 4 repeats a couple of times—eventually, though, it stops doing this.

![recorded](https://user-images.githubusercontent.com/68839/29134143-a0eae2e6-7cea-11e7-9ffa-b866fd5d9d3b.gif)

this wouldn't be so bad except (a) it's unpredictable when it will happen (so sometimes I end up hitting return when it didn't happen, and exit multiple-cursors) and (b) it's sometimes undesirable—I've got all the cursors I want, and then it's waiting for me to run some function, and I don't know how to exit out of that selection mode without also exiting multiple-cursors.

**Comment by magnars** [comment]
Multiple cursors does not work well with `M-x`. You need to bind the commands to keys. I've tried to make that clearer in the README now. Thanks.
