### ISSUE TITLE
End key moves only highlighted cursor

### ISSUE THREAD

**Issue by lobisquit** [magnars/multiple-cursors.el#300]
I just bumped into an unexpected behaviour of multi-line editing.

When selecting a region, cursors are put at the beginning of the line, as expected using `mc/edit-lines`.
After writing something, the `Home` key makes _all_ cursors get back to the start, while `End` key makes only the highlighted cursor move to the end of its line.

Is there any way to make `End` behave as `Home`? It would be very useful in my common workflow.

Thank you very much

PS. I'm using `emacs 25.2` on Arch Linux with the most recent `spacemacs` version.

**Comment by magnars** [comment]
Please check your `~/.emacs.d/.mc-lists.el` file for the command in question. At some point you have probably answered "no" to the question "Do this for all cursors?", landing the command in the `mc/cmds-to-run-once`-list. Move the command to the `mc/cmds-to-run-for-all` and evaluate the buffer to resolve this issue.

**Comment by lobisquit** [comment]
Everything works now!
Thank you very much for solving this silly problem :wink:
