### ISSUE TITLE
Documented way to add newlines in multiple-cursors mode produces error at startup

### ISSUE THREAD

**Issue by terrycloth** [magnars/multiple-cursors.el#301]
I've been trying out multiple-cursors (using Spacemacs) and I'm generally liking it so far. I noticed your README mentions a way to make the RET key enter a newline as normal, so I decided to try it. Here's a snippet of my user config block, which gets loaded by Spacemacs after all other plugins and default settings.

``` elisp
(defun dotspacemacs/user-config ()
  (define-key mc/keymap (kbd "<return>") nil)
  ;; Map multiple-cursors commands and some clipboard copy/paste commands
  ;; to the C-S-c prefix...
)
```

When I reloaded the Emacs config right after adding that `mc/keymap` line, it seemed to work as expected: I could add new cursors, add a newline to each cursor with <kbd>Return</kbd>, and quit multiple-cursors with <kbd>C-g</kbd>. However, I get an error when I *restart* Emacs, and suddenly none of the multiple-cursors keyboard shortcuts work anymore. The Messages buffer reports this:

> `(Spacemacs) Error in dotspacemacs/user-config: Symbol’s value as variable is void: mc/keymap`

Commenting out the keymap line and restarting Emacs again fixes all the other shortcuts. The above error message sounds to me like the documentation might be out of date? If there's something *I'm* doing wrong, I'm not sure what it is.

**System info**

- OS: Fedora 25 Workstation x86_64 (gnu/linux)
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- multiple-cursors-20170713.1847 (latest melpa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: `(html vimscript javascript shell-scripts markdown helm emacs-lisp)`
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by jtamagnan** [comment]
It seems like `(define-key mc/keymap (kbd "<return>") nil)` is being called before the multiple-cursors project is loaded. Can you move things around so that that is no longer the case?

You can also try to eval that code after multiple-cursors has been loaded. Maybe something like:
```
(with-eval-after-load 'multiple-cursors
    mc/keymap)
```

**Comment by terrycloth** [comment]
Ah! Yes, that did the trick, thanks.
