### ISSUE TITLE
[Wish] (Un)expand cursors in only one direction like select region

### ISSUE THREAD

**Issue by fzzy** [magnars/multiple-cursors.el#309]
It's too difficult to unmark cursors now 
Please add option so you could mark cursors similar to how select region works
You could only expand cursors in one direction, but it would be easier to unmark them at least

**Comment by jtamagnan** [comment]
Hey thank you for the suggestion. Could you describe the command you'd like implemented a bit more fully, how it could be used, what you mean by "similar to how select region works". Maybe some examples or screenshots could help?

**Comment by fzzy** [comment]
Here is a shoddy paint for illustration
https://i.imgur.com/g7M0ohm.png

**Comment by nispio** [comment]
Have you checked out the command `mc/mark-more-like-this-extended`?  It has behavior like what I think you are trying to describe in the picture.

**Comment by jtamagnan** [comment]
You can also press `M-v` to rotate the current cursor in the opposite direction. Once you've created all of your cursors `M-v` will bring you to the bottom one

**Comment by jtamagnan** [comment]
@fzzy did that work for you? If so feel free to close this

**Comment by fzzy** [comment]
it kinda works yeah
