### ISSUE TITLE
Add note to documentation about the utility of zap-to-char (M-z)

### ISSUE THREAD

**Issue by jwiegley** [magnars/multiple-cursors.el#310]
One thing I was missing with multiple-cursors (which is simply *fantastic*) is that i-search will not let me jump all the cursors ahead to a common character.  For example, in csv-mode, I wanted to change this:

```csv
navi git@github.com:alphapapa/navi.git
outshine git@github.com:alphapapa/outshine.git
helm-navi git@github.com:emacs-helm/helm-navi.git
helm-describe-modes git@github.com:emacs-helm/helm-describe-modes.git
```

into this:

```csv
navi,site-lisp,subtree,git@github.com:alphapapa/navi.git,
outshine,site-lisp,subtree,git@github.com:alphapapa/outshine.git,
helm-navi,site-lisp,subtree,git@github.com:emacs-helm/helm-navi.git,
helm-describe-modes,site-lisp,subtree,git@github.com:emacs-helm/helm-describe-modes.git,
```

I put cursors at the beginning of each line, but `C-M-f` does not advance to the space, since that's not how words are defined in `csv-mode`, apparently. So the question arises: how do I advance all the cursors to the space, so that I can add in the new content there?

`C-s` is how I would do this normally, but here's my workaround that works with multiple-cursors:

    M-z <space> DEL , C-b C-y

Because M-z zaps to a particular character *and puts the deleted text on the kill-ring*, I restore the text after any editing has taken place.  Once I discovered this shortcut, I find myself using it quite often, so I thought I'd mention it here.

**Comment by nispio** [comment]
Just in case you aren't aware, [`phi-search`](https://github.com/zk-phi/phi-search) is an `isearch`-like command that is compatible with multiple-cursors mode.  In other words, using `C-s` to seek forward to the next cursor will work as you expect if you re-bind `C-s` to `phi-search` then your above scenario should work how you expect.

Example from `phi-search` README:
![phi-search example](https://github.com/zk-phi/phi-search/raw/master/img/search.gif)

**Comment by jwiegley** [comment]
Ah, perfect, I'll find a way to bind C-s to phi-search only when multiple-cursors are active. Otherwise, I have C-s bound to swiper. Thank you!

**Comment by nispio** [comment]
I imagine you figured this out as well, but for completeness:

```
(eval-after-load "multiple-cursors"
  (progn
    (define-key mc/keymap (kbd "C-s") #'phi-search)))
```
