### ISSUE TITLE
Cannot input text from kbd in Org mode (spacemacs holy-mode)

### ISSUE THREAD

**Issue by 4mitch** [magnars/multiple-cursors.el#312]
Hello! Thanks for great tool! It makes Emacs UX more familiar with N++ and VSCode ;)
Just want to clarify. I also use spacemacs but in holy-mode (not evil). And MC seems works ok for example in *scratch* or simple code files. 
But in Org mode `mc/edit-lines ` did insert multiple cursors on each line of marked region (with C-SPC), and allow to move them and delete chars, BUT I cannot insert any chars from KBD. 
Could it be linker with #216 (evil mode) or what?
Does Org mode uses Transient-mark-mode (#52) ? How to check it?

**Comment by nispio** [comment]
Multiple cursors is compatible with org mode in my experience, but I am not
a spacemacs user.  It would be helpful if you could describe some specific
steps to reproduce what you are seeing.  Also, if it is not doing what you
expect, please describe what it is doing instead.

Another helpful thing would be to use `C-h c` plus some letter to make sure
that your unmodified letter keys are bound to self-insert.

**Comment by 4mitch** [comment]
It looks like this
![mc-edit-lines-demo](https://user-images.githubusercontent.com/2834246/33598294-43513646-d9b3-11e7-8ff4-112e1c41c62e.gif)

Well, may be specemacs holy-mode equals to evil-mode in context of #216 issue :/ I will try without spacemacs as well

**Comment by nispio** [comment]
Find the file `~/.emacs.d/.mc-lists.el` and move the line containing `org-self-insert-command` from the "command to run once" list to the "commands to run for all" list.  Then `M-x eval-buffer` in that buffer to apply the change.

At one point when you first used multiple cursors with org mode, (whether you realized or not) you were prompted "do org-self-insert-command for all cursors (y or n)" and you replied "n".

**Comment by 4mitch** [comment]
Ahhh! Great! Stupid me :)
Thank you a lot for help and sorry for disturbing!
