### ISSUE TITLE
unable to enter line breaks with C-j

### ISSUE THREAD

**Issue by yilkalargaw** [magnars/multiple-cursors.el#313]
when ever using multiple cursors and pressing C-j I get an error in the minibuffer like this

Debugger entered--Lisp error: (void-variable <the last word>)
  eval(<the last word> nil)
  elisp--eval-last-sexp(t)
  eval-last-sexp(t)
  eval-print-last-sexp(nil)
  funcall-interactively(eval-print-last-sexp nil)
  call-interactively(eval-print-last-sexp nil nil)
  command-execute(eval-print-last-sexp)

**Comment by nispio** [comment]
You haven't provided nearly enough information, but I bet that I can guess
your problem.  You are pressing C-j in the scratch buffer, which does more
than just insert a newline. It evaluates the lisp expression immediately
before the cursors and executes it, inserting the result into the buffer as
well.  If you are executing that command while in multiple cursors mode and
there is no lisp expression before even one of the cursors (like perhaps
you are at the beginning of a line) you would see that error. That is
expected, and has nothing to do with multiple cursors mode.

If you believe this does not describe your issue, please provide a more
detailed bug report, with steps to reproduce the error.

**Comment by nispio** [comment]
I am going to assume that your issue was as I described, and is not related to multiple-cursors.
