### ISSUE TITLE
I think MC don't work with GTK terminals

### ISSUE THREAD

**Issue by thomasluquet** [magnars/multiple-cursors.el#314]
hi, 
i try with this simple config :
```
(require 'multiple-cursors)
global-set-key (kbd "M-SPC") 'set-rectangular-region-anchor)
(global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
(global-set-key (kbd "C->") 'mc/mark-next-like-this)
(global-set-key (kbd "C-<") 'mc/mark-previous-like-this) 
(global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)
```
It work perfectly when i use emacs in `xterm` or emacs in windows mode.

But when i try with `xfce terminal` , `sakura` or `terminator` , the binding (`C-> , C-< , C-c C-<`) don't works... (It write < and > )

Any idea ?

**Comment by magnars** [comment]
That might be. Try binding it to something else.

**Comment by thomasluquet** [comment]
i put it on F9/F10/F11 , it works...
