### ISSUE TITLE
[feat-req] mc/mark-all-like-this-symbol 

### ISSUE THREAD

**Issue by philiparvidsson** [magnars/multiple-cursors.el#315]
**Problem:**

There is no mark-all-equivalent for the `mark-next-like-this-symbol`. The key point is the last part of the description for that function:

mc/mark-next-like-this-symbol: Adds a cursor and region at the next part of the buffer forwards that matches the current region, **if no region is selected it selects the symbol at the point.**

**Solution:**

Implement `mark-all-like-this-symbol` which uses region if there is one, otherwise tries to use the symbol at point.

**Comment by magnars** [comment]
I think you might be looking for `mc/mark-all-dwim` which does this. First in the current context, then the entire buffer.

**Comment by philiparvidsson** [comment]
Not sure if I'm using it wrong, `mc/mark-all-dwim` is giving me `"Mark a region to match first."`

**Comment by magnars** [comment]
Hm, that's weird. I use mc/mark-all-dwim like this multiple times per day with no region.

> (mc/mark-all-dwim ARG)
> 
> Tries even harder to guess what you want to mark all of.
> 
> If the region is active and spans multiple lines, it will behave as if ‘mc/mark-all-in-region’. With the prefix ARG, it will call ‘mc/edit-lines’ instead.
>
> **If the region is inactive or on a single line, it will behave like ‘mc/mark-all-like-this-dwim’.**

How does `mc/mark-all-like-this-dwim` work for you?

**Comment by philiparvidsson** [comment]
Same thing. I don't understand the argument it wants, maybe that's the problem. Do I need to use a particular argument? It won't let me use `nil` so I've tried 0, 1 and (point).

**Comment by magnars** [comment]
Try binding it to a key directly.

**Comment by philiparvidsson** [comment]
I can't do that unfortunately because this is a function bound to a key that needs to do something else first. Is there any way around it?

**Comment by magnars** [comment]
First step is checking if it works as intended when bound directly to a
key. After that, just eval the function after adding a log message with the
params. Run it again. Now you know what params should work.
fre. 5. jan. 2018 kl. 13:44 skrev Philip Arvidsson <notifications@github.com

**Comment by philiparvidsson** [comment]
Solved by making my function `(interactive "P")` and passing the argument on to multiple-cursors. Sometimes getting the error `Wrong type argument: integer-or-marker-p, nil` but that is something else that I have to figure out.
