### ISSUE TITLE
bug: add two `(` for the first cursor when prompt for `do xxx for all cursors (y or n)` in `paredit-mode`.

### ISSUE THREAD

**Issue by cmal** [magnars/multiple-cursors.el#319]
I am using this in Clojure(Script) mode, when I add multiple cursors for the following code:
```
(case cate
    :1year ^(in-n-year? 1 item ymd-slash-formatter)
    :3year ^(in-n-year? 3 item ymd-slash-formatter)
    :5year ^(in-n-year? 5 item ymd-slash-formatter))
```
The `^` is the position where I put the points.
Then (the first time) I do `M-(` to do ` paredit-wrap-round`, it will prompt me: 
```
Do paredit-wrap-round for all cursors? (y or n) y
```
Then I got this:
```
(case cate
    :1year ((^(in-n-year? 1 item ymd-slash-formatter)))
    :3year (^(in-n-year? 3 item ymd-slash-formatter))
    :5year (^(in-n-year? 5 item ymd-slash-formatter)))
```
Note the first cursor got two `(`s instead of one.
(After this, when it does not prompt me the (y or n), the `paredit-wrap-round` command runs correctly.)

**Comment by nispio** [comment]
I am unable to reproduce this.  Are you able to reproduce this issue after removing `paredit-wrap-round` from `mc/cmds-to-run-for-all`?  If so, can you provide more detail about how you add your cursors?  I am wondering if you might have had two cursors on the top line the first time and not realized it.

**Comment by cmal** [comment]
Sorry for that. It must be I added two cursors at the first line's `^`.
There is a problem that often makes me confused: The first cursor is added by default, and press mouse on the point again will make it two cursors (at the same position), but press mouse (again) on the other cursors will toggle that cursor. But what so ever, it is another problem. So close this issue. Thanks a lot! @nispio
