### ISSUE TITLE
Atom like behavior

### ISSUE THREAD

**Issue by consciencia** [magnars/multiple-cursors.el#320]
Is there a way how to enable atom-like behavior?
I mean, command for spawning/deleting new cursor at the bottom/up line etc.

**Comment by nispio** [comment]
It may surprise you to learn that most of us are emacs users.  As such,
"atom-like behavior" does not help me to know what you are trying to
achieve.  Please describe the behavior you are trying to achieve as if I
have never used Atom.

Before you do, please make sure to read the Readme and try out the basic
commands described there. Creating and deleting cursors are both supported
by this package, and the Readme will give a much more thorough explanation
than you can expect to get in a bug report (unless you have described a
very specific behavior that you believe multiple-cursors does not provide.)

>

**Comment by nispio** [comment]
Glad you figured it out.  Happy editing!
