### ISSUE TITLE
Can't limit multiple cursors movement to end of line

### ISSUE THREAD

**Issue by MrCStone** [magnars/multiple-cursors.el#321]
When I make multiple cursors, either with set-rectangle-region-anchors or other ways, whatever I do I can't make them all move to the end of line and stay there, for example for adding an extension to multiple lines in dired. 

They just go beyond the end of line, and some cursors dissappear. Is there a way to make it work, is it a bug, or am I doing it all wrong?

**Comment by nispio** [comment]
When using `set-rectangle-region-anchors`, you are not in multiple cursors mode until you press enter.   
 Until then, you are still just selecting the rectangle region.  For example, this will put a cursor on four lines and then move the cursor to the end of each of them:

1. `M-x set-rectangle-region anchors`
2. `C-n C-n C-n`
3. `<return>`
4. `C-e`

Also, there are lots of other ways to do what you are trying to do.  What do you mean by the "other ways" that you have tried. One of many alternative ways that you could achieve this is to set the mark at the first line you want to change, move the point down to the last line you want to change, and then run `mc/edit-lines`.

**Comment by nispio** [comment]
Were you able to resolve this?  I will close this issue for now.  Feel free to come back with steps to reproduce the problem if it persists.

**Comment by MrCStone** [comment]
Hey!! Sorry, I completely forgot I opened the issue!! Yeah,everything works
fine now! There was a functio  that I was missing! Select all ends of lines
or something
