### ISSUE TITLE
Multiple cursors insert not working with outline-minor-mode

### ISSUE THREAD

**Issue by grahamas** [magnars/multiple-cursors.el#323]
In a *scratch* buffer, after exiting all minor modes, I type a few lines of text. I can make multiple cursors and edit multiple lines just fine.

Now I enable outline-minor-mode. Attempting the same multiple cursors edits, I am able to create the cursors, but on typing, new text only appears at one cursor (the last cursor created). Strangely, navigation and backspace work fine.

Does anyone know why this might be?

I'm using Emacs 25.2.2 and multiple-cursors from elpa 20170908.

**Comment by nispio** [comment]
Your first step should be to find out what command is getting invoked when typing in that mode.  From within a buffer in `outline-minor-mode`, press `C-h c` followed by some un-modified letter or digit and verify that it is bound to `self-insert-command`.  If it is bound to anything other than that, check your `~/.emacs.d/.mc-lists.el` and make sure that the command in question is listed in the group of commands to run for all cursors.

If any of this is unclear, feel free to ask.  Good luck.

**Comment by grahamas** [comment]
Thank you. I must have accidentally hit 'n' when it prompted me for whether I wanted `outshine-self-insert-command` to run on all cursors. It and `org-self-insert-command` were both under `cmds-to-run-once`.
