### ISSUE TITLE
Moving cursor up/down breaks normal cursor behaviour

### ISSUE THREAD

**Issue by pstray** [magnars/multiple-cursors.el#325]
Normally when moving up or down, the cursor tries to keep itself in temporary-goal-column.  This variable should be stored for each fake cursor, setting it before next-line and previous-line, and storing it after. Otherwise the fake cursors jump all over the place if you move up an down through lines that are shorter then the one you started at.

**Comment by nispio** [comment]
Sorry, I did not mean to close the issue.  I agree that the behavior with regards to goal columns can be erratic.  This proposal is probably worth doing, but I expect that the level of effort required to implement and test is fairly high.

**Comment by magnars** [comment]
Could this be solved by adding `temporary-goal-column` to `mc/cursor-specific-vars`?

**Comment by pstray** [comment]
Yes, that does the trick :)

**Comment by magnars** [comment]
Excellent. 👍 Merged.
