### ISSUE TITLE
Multiple-Cursors mode disabled

### ISSUE THREAD

**Issue by haluk** [magnars/multiple-cursors.el#330]
After I turn-off multiple cursors with C-g, I keep getting "Multiple-Cursors mode disabled" message for my every single actions such as opening a new file, killing buffer etc. I have to press enter to close the message and perform the action. I'm using prelude starter kit.

My Emacs version: GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-20 on lcy01-07, modified by Debian

**Comment by nispio** [comment]
If the "Mutliple-Cursors mode disabled" message is an error message, then use `M-x toggle-debug-on-error`, repeat the steps that cause the error, and then paste the traceback here.

Can you try without prelude and confirm that it works as expected?

It may also be helpful to show how you are setting up MC in your init, as well as how you are using it.  For example, are you adding cursors with the mouse?  From a keybinding?  From an `M-x` command?

**Comment by haluk** [comment]
I didn't see any messages after toggling debug on error. But I still see the same message in *Messages* buffer. I use keybinding to activate mc.

This is how I add mc on my personal config in prelude (~/.emacs.d/personal/preload/haluk_preload.el)
```
;; Multiple-cursors
(setq multiple-cursors-mode t)
(global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
(global-set-key (kbd "C->") 'mc/mark-next-like-this)
(global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
(global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)
```

**Comment by nispio** [comment]
The mode itself, `multiple-cursors-mode`, is a minor mode that should only be active _when you have more than one active cursor_ and does not need to be invoked directly by you.  In other words, you should remove the `(setq multiple-cursors-mode t)` from your config.

Functions like `mc/mark-next-like-this` already end with a call to `mc/maybe-multiple-cursors-mode`, which decides whether or not `multiple-cursors-mode` should be activated based on the number of active cursors.

If removing that line from your config does not solve the problem, feel free to come back and we can poke at it some more.

**Comment by haluk** [comment]
Thank you, it worked!

I'm closing the issue.
