### ISSUE TITLE
Is it possible to disable active multiple-cursors when click?

### ISSUE THREAD

**Issue by jrfferreira** [magnars/multiple-cursors.el#331]
Hello,

I use multiple-cursors a lot, but I have the bad habit of forgetting them active and use the mouse, so, for me it would be nice if I could cancel the active multiple-cursors after a click with `<mouse-1>`.

Does anyone know how to do it without side effects?

This is my current definitions:
```
  (with-eval-after-load 'multiple-cursors
    (define-key mc/keymap (kbd "<return>") nil))
  (global-set-key (kbd "C->") 'mc/mark-next-like-this)
  (global-set-key (kbd "C-<") 'mc/mark-previous-like-this)

  (global-set-key (kbd "C-M-<") 'mc/mark-all-like-this)
  (global-set-key (kbd "C-M->") 'mc/edit-lines)

  (global-unset-key (kbd "C-S-<down-mouse-1>"))
  (global-set-key (kbd "C-S-<mouse-1>") 'mc/add-cursor-on-click)
```

Thanks!

**Comment by nispio** [comment]
How about something like this?

    (with-eval-after-load 'multiple-cursors
      (defun mc/mouse-quit ()
        "Deactivate mark if there are any active, and exit multiple-cursors-mode."
        (interactive)
        (if (use-region-p)
            (deactivate-mark))
        (multiple-cursors-mode 0))
      (define-key mc/keymap [down-mouse-1] #'mc/mouse-quit))

You could add the body of that `with-eval-after-load` to the one you already have.  I tested this only enough to make sure that it did what I expected when clicking text in the buffer.  I expect it to do what you expect, but you may find corner cases that you have to click something twice.  Still better than forgetting that you are MC mode though.

**Comment by jrfferreira** [comment]
Thank you @nispio! It is exactly what I'm looking for.
