### ISSUE TITLE
Enter "\" with multiple cursors

### ISSUE THREAD

**Issue by FrancescoCadei** [magnars/multiple-cursors.el#343]
Hi, i can't enter "\\" with multiple cursors (only the first is added).

**Comment by Fuco1** [comment]
Can you be a bit more specific?  What mode, what packages you use, a minimal repro, what exactly you type?

**Comment by FrancescoCadei** [comment]
For example in LaTeX mode.
I use "smartparens" and "AUCTeX".

When i select multiple cursors (also with "mc/add-cursor-on-click") and then type `\`, only the first is insert.

**Comment by FrancescoCadei** [comment]
Yes you are right. Big thanks!
