### ISSUE TITLE
Disable prompt and enable all commands for all cursors

### ISSUE THREAD

**Issue by ianpan870102** [magnars/multiple-cursors.el#345]
First of, I REALLY love this package! There's a problem though: After I accidentally hit `no` when it first prompted if I should do C-e (end of line) for all cursors, there seems to be no way to revert the no to a yes anymore.... I've even come so far to reinstalling the package but it seems to remember (somehow) that I ``didn't'' want to perform C-e (BUT I ACTUALLY DO...................)

**Comment by magnars** [comment]
Please check your `~/.emacs.d/.mc-lists.el` file for the command in question. At some point you have probably answered "no" to the question "Do this for all cursors?", landing the command in the `mc/cmds-to-run-once`-list. Move the command to the `mc/cmds-to-run-for-all` and evaluate the buffer to resolve this issue. 🙂

**Comment by ianpan870102** [comment]
Thanks Magnar, works like a charm now!!
