### ISSUE TITLE
Can't type "//" (for c++ comments) at multiple cursors

### ISSUE THREAD

**Issue by tinloaf** [magnars/multiple-cursors.el#346]
I'm trying to prepend `//` to multiple lines to comment out some c++ code. However, this seems not to work with multiple cursors for some reason:

![screencast](https://user-images.githubusercontent.com/442687/47216433-39f19b80-d3a5-11e8-8219-61f94820d562.gif)

For some reason, the `//` is only added to the first line. Am I doing something wrong or is this a bug?

I'm using multiple-cursors straight from MELPA with emacs 25.2.2. The command I used to create multiple cursors was `mc/mark-next-like-this`.

Thanks a lot!

**Comment by magnars** [comment]
Please check your `~/.emacs.d/.mc-lists.el` file for the command in question. At some point you have probably answered "no" to the question "Do this for all cursors?", landing the command in the `mc/cmds-to-run-once`-list. Move the command to the `mc/cmds-to-run-for-all` and evaluate the buffer to resolve this issue. :)

**Comment by tinloaf** [comment]
D'Oh, indeed! Thanks, sorry for the noise.
