### ISSUE TITLE
mc/cursor-bar-face lengthens line

### ISSUE THREAD

**Issue by ddovod** [magnars/multiple-cursors.el#347]
Hi guys.
Looks like new `mc/cursor-bar-face` works not like original bar cursor in emacs.
The thing is original cursor doesn't affect text at all, but when I spawn second (3rd etc) cursor, it lengthens line like there's 1px gap in the place where cursor is spawned.
Actually I was ok with old behavior, where my main cursor is bar and all others are "default" not bar cursors, and also I can distinguish my main cursor among others.
So, is there a solution to not make fake cursors spend additional space?
If no, can I use old style cursors event if my default cursor style is bar?
Thank you very much!

**Comment by ddovod** [comment]
Hi guys. Sorry for disturbing, but is there any chance to work this issue around? Thank you

**Comment by jtamagnan** [comment]
Hi @ddovod when I implemented this I found no way of using the overlay system to mimic the original bar cursor which is why it works the way it does now. To use the default style fake cursors regardless of your current cursor type, you should be able to add this to your config:
```
(defun mc/cursor-is-bar
  nil)
```

**Comment by ddovod** [comment]
Awesome, that's exactly what I need, thank you very much!
