### ISSUE TITLE
Issue using math symbols in fortran mode

### ISSUE THREAD

**Issue by jrstromme** [magnars/multiple-cursors.el#353]
When I am in fortran mode, '*', '/', '-', '+' are only written with the primary cursor. '=' works fine as do other symbols.

I am not too proficient with emacs so I am not entirely sure how to isolate why this is occurring.

Thanks.

**Comment by magnars** [comment]
Please check your `~/.emacs.d/.mc-lists.el` file for the command in question. At some point you have probably answered "no" to the question "Do this for all cursors?", landing the command in the `mc/cmds-to-run-once`-list. Move the command to the `mc/cmds-to-run-for-all` and evaluate the buffer to resolve this issue.

**Comment by jrstromme** [comment]
Hi, thanks so much! I needed to move `f90-electric-insert` to `mc/cmds-to-run-for-all`.
