### ISSUE TITLE
upcase-region (via jlf)

### ISSUE THREAD

**Issue by magnars** [magnars/multiple-cursors.el#74]
upcase-region seems to operate only on the lowermost region (where the "real" cursor is)

**Comment by jtamagnan** [comment]
This is no longer an issue and should be closed. I don't know when it was fixed but it works on `GNU Emacs 25.0.92.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
 of 2016-04-07`

**Comment by magnars** [comment]
Thanks
